### ISSUE TITLE
Missing artifact com.jensfendler:ninja-quartz:jar:0.0.1

### ISSUE THREAD

**Issue by danielsawan** [FendlerConsulting/ninja-quartz#1]
Hi there.
I am actualy trying to use your module but i get an error 

Missing artifact com.jensfendler:ninja-quartz:jar:0.0.1

As if the your jars was not deployed on maven repo ?

**Comment by jfendler** [comment]
You are right - I am in the process of pushing to Maven Central (and already updated the docs accordingly), but didn't manage so far.
I hope to solve the issues within the next few days. In the meantime, please do the following:
- clone the GIT repository
- mvn clean compile install
  and use version 0.0.1-SNAPSHOT in your dependency.

@danielsawan UPDATE: the release build finally went through. Waiting for sync to Maven Central now.
