### ISSUE TITLE
Follow the tutorial to use ninja-quartz, but Scheduled jobs not running

### ISSUE THREAD

**Issue by j2hongming** [FendlerConsulting/ninja-quartz#2]
Hi FendlerConsulting, 
thank you for building this project.

I follow the tutorial to use ninja-quartz, but Scheduled jobs not running.

My development environment
- JDK 1.7
- ninja 5.7.0
- jetty 9.2.10.v20150310

There are some information in ninja SuperDevMode:
the quartz scheduler runs successfully

```
15:16:38.217 [NinjaJetty] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.2) 'NinjaQuartz' with instanceId 'NON_CLUSTERED'                                                                
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally. NOT STARTED.                                                                                                 
  Currently in standby mode.                                                                                   
  Number of jobs executed: 0                                                                                   
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.                                     
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered. 
```

but there are some exception about the job,  it's related to NoSuchMethodError

```
15:16:38.249 [NinjaQuartz_Worker-1] ERROR c.j.ninjaquartz.job.NinjaQuartzTask - Exception during execution of quartz task nqJ-mySecondScheduledMethod/nqJG-schedule.MySchedules.java.lang.NoSuchMethodError: java.lang.reflect.Method.getParameterCount()I
    at com.jensfendler.ninjaquartz.NinjaQuartzScheduleHelper$1.execute(NinjaQuartzScheduleHelper.java:238) ~[ninja-quartz-0.0.5.jar:na]
    at com.jensfendler.ninjaquartz.job.AbstractNinjaQuartzJob.execute(AbstractNinjaQuartzJob.java:107) ~[ninja-quartz-0.0.5.jar:na]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.2.jar:na]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.2.jar:na]
```

**Comment by jfendler** [comment]
Hi @j2hongming 

The exception indicates that the method you are trying to schedule has invalid parameters. My guess would be you have specified some additional parameters (other than just a JobExecutionContext).

As per the documentation, scheduled methods must take one of two possible forms:
`void methodName( void )`
or
`void methodName( JobExecutionContext context )`

Hope this helps.

**Comment by j2hongming** [comment]
Hi @jfendler , thank for replying

The scheduler Class as follows:

```
public class MySchedules {

    final static Logger logger = LoggerFactory.getLogger(MySchedules.class);

    @QuartzSchedule(cronSchedule = "0/10 * * * * ?")
    public void myFirstScheduledMethod() {
        // do your thing
    }


    // Use a cron schedule as specified in Ninja's application.conf property 'schedule.secondMethod' 
    @QuartzSchedule(cronSchedule = "schedule.secondMethod")
    public void mySecondScheduledMethod(JobExecutionContext context) {
        // do your thing
        // you can access the Quartz job's JobExecutionContext here as well
        JobKey jobKey = context.getJobDetail().getKey();
        logger.info("SimpleJob says: " + jobKey + " executing at " + new Date());
    } 
```

install and bind in `config.Module class`

```
public class Module extends AbstractModule {   

    protected void configure() {
        install( new NinjaQuartzModule() );
        // bind your injections here!
        bind(MySchedules.class);
    }

}
```

property in `application.conf`

`schedule.secondMethod=0/1 * * * * ?`

but the same exception happens in ninja SuperDevMode

Is there other configuration or info I doesn't mention ?

[UPDATE]
I found [this article](https://jira.spring.io/browse/SPR-11245) and it says because `getParameterCount()` method is specific to Java 8 and will cause projects using prior versions of Java to throw an exception.
and [this aritcle](https://github.com/peholmst/vaadin4spring/issues/25) suggest to the `getParameterTypes().length`

**Comment by jfendler** [comment]
@j2hongming very nice catch. Thanks!

I've pushed an updated version (0.0.6) using `getParameters().length` to maven. It should be available soon..

**Comment by j2hongming** [comment]
@jfendler , thank for your help!
After I reset dependency in pom.xml to 0.0.6 and rebuild my project, there are some information in ninja SuperDevMode:

```
09:31:41.962 [NinjaQuartz_Worker-1] ERROR c.j.ninjaquartz.job.NinjaQuartzTask - Exception during execution of quartz task nqJ-mySecondScheduledMethod/nqJG-schedule.MySchedules.java.lang.NoSuchMethodError: java.lang.reflect.Method.getParameters()[Ljava/lang/reflect/Parameter;
    at com.jensfendler.ninjaquartz.NinjaQuartzScheduleHelper$1.execute(NinjaQuartzScheduleHelper.java:238) ~[ninja-quartz-0.0.6.jar:na]
    at com.jensfendler.ninjaquartz.job.AbstractNinjaQuartzJob.execute(AbstractNinjaQuartzJob.java:106) ~[ninja-quartz-0.0.6.jar:na]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.2.jar:na]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.2.jar:na] 
```

I found that [method name](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Method.html) in `java.lang.reflect.Method` is `getParameterTypes`.

Thanks

**Comment by jfendler** [comment]
@j2hongming I'm sorry for the improper 0.0.6 release. I have updated the respective code again in 0.0.7, and also updated pom.xml to ensure Java7 compatibility. The issue should be fixed now.

Also, there is now support for guice injection of parameters into your methods. I.e. you are no longer limited to no-arguments or single-JobExecutionContext-arguments scheduled methods, but can use parameters of any type guice knows about.

Hope this helps. Please let me know if you still experience any issues.

**Comment by j2hongming** [comment]
@jfendler Thanks a lot
it works like a charm!
